on:
  workflow_call:
    secrets:
      RENOVATE_APP_CLIENT_ID:
        required: true
      RENOVATE_APP_PRIVATE_KEY:
        required: true
    inputs:
      dryRun:
        type: boolean
        default: ${{ github.event_name == 'pull_request' }}

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    env:
      RENOVATE_DRY_RUN: ${{ inputs.dryRun && 'full' || '' }}
      RENOVATE_ONBOARDING: false
      RENOVATE_REPOSITORIES: ${{ github.repository }}
      RENOVATE_EXTENDS: config:recommended,helpers:pinGitHubActionDigestsToSemver
      RENOVATE_CUSTOM_MANAGERS: >-
        [
          {
            "customType": "regex",
            "description": "Update *[-_]version parameters",
            "managerFilePatterns": [".github/workflows/*"],
            "matchStrings": [
              "[-_]version:\\s*(?<currentValue>[0-9.]+)\\s*# renovate: datasource=(?<datasource>[a-z-]+) depName=(?<depName>\\S+)",
              "[-_]version:\\s*(?<currentDigest>[a-f0-9]{40})\\s*# renovate: datasource=(?<datasource>[a-z-]+) depName=(?<depName>\\S+) packageName=(?<packageName>\\S+) currentValue=(?<currentValue>\\S+)"
            ]
          }
        ]
      RENOVATE_COMMIT_BODY: >-
        {{#each upgrades}}New-{{{datasource}}}-version: {{{depName}}}{{#if newVersion}}=={{{newVersion}}}{{else if newDigest}}=={{{newDigest}}}{{/if}}\n{{/each}}
      LOG_LEVEL: debug
      RENOVATE_LOG_FILE: /tmp/renovate-log.jsonl
      RENOVATE_LOG_FILE_LEVEL: warn
    steps:
    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        client-id: ${{ secrets.RENOVATE_APP_CLIENT_ID }}
        private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
        permission-contents: write
        permission-issues: write
        permission-workflows: write
        # When run from a PR, it should be in dry-run mode, so shouldn't create PRs.
        # But if it did, it's not too hard to imagine a PR creation loop. So
        # let's add another layer of protection.
        permission-pull-requests: "${{ github.event_name == 'pull_request' && 'read' || 'write' }}"
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
      with:
        renovate-version: 43.214.4 # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
        token: ${{ steps.app-token.outputs.token }}
    - name: Fail if there are warnings or errors
      run: |
        cat "$RENOVATE_LOG_FILE"
        [ ! -s "$RENOVATE_LOG_FILE" ]
